### ISSUE TITLE
Text shifts down 1px on selection

### ISSUE THREAD

**Issue by ktmn** [chmln/betterWhiteSpace#2]
Works great, looks great, but when I select text it moves down by 1px. 

In the demo gif it seems to actually move left, but that doesn't happen to me.

Using Droid Sans Mono for Powerline font.

Any way to correct it?

**Comment by ktmn** [comment]
Changing to a different font size fixed it.

**Comment by victorwpbastos** [comment]
For me, even with a different font size, the behavior still persists.

**Comment by ktmn** [comment]
Yeah ran into the problem again as well on Windows. 

Ended up editing [this line](https://github.com/chmln/betterWhiteSpace/blob/master/src/extension.ts#L86) to use the same font as the editor uses to fix it.

**Comment by victorwpbastos** [comment]
How did you do this?

Em 22 de nov de 2017 8:36 AM, "ktmn" <notifications@github.com> escreveu:

**Comment by ktmn** [comment]
I went to `%userprofile%\.vscode\extensions\chmln.better-whitespace-1.0.1\out\src` and edited the `extension.js` file. 

After making the change you have to run "Reload window" from the command palette of VSCode.

This change will get overwritten when the plugin is updated though. Could be possible to bump the version in `package.json` to something large, then that could disable updates, but I haven't tested it.

**Comment by victorwpbastos** [comment]
I changed to:

```js
const emDashFont = editorConfig.get('fontFamily');
```

So the extension uses the same font you are using in vscode. I'll make a PR.
